# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
 - job: Job1
   dependsOn: Job3
   steps:
   - script: echo j1 Hello, world!
     displayName: 'Run a one-line script for j1'

 - job: Job2
   steps:
   - script: echo j2 Hello, world!
   displayName: 'Run a one-line script for j2'

 - job: Job3
   dependsOn:
   - Job2
   - Job4
   steps:
   - script: echo j3 Hello, world!
   displayName: 'Run a one-line script for j3'

 - job: Job4
   dependsOn: Job2
   steps:
   - script: echo j4 Hello, world!
   displayName: 'Run a one-line script for j4'




